event.subscription.annotation.fqn=org.smartbit4all.api.invocation.EventSubscription
event.subscription.annotation.name=EventSubscription
event.subscriber.info.api=api
event.subscriber.info.event=event
event.subscriber.info.channel=channel
event.publisher.invocation.api.fqn=org.smartbit4all.api.invocation.InvocationApi
event.publisher.method.name=publisher
command.testEventAnnotationScanner.name=Test EventAnnotationScanner
command.testEventAnnotationScanner.desc=Runs EventAnnotationScanner on the selected Java file
command.testEventAnnotationScanner.label=Test EventAnnotationScanner